"""
Django settings for crypto project.

Generated by 'django-admin startproject' using Django 3.2.12.
"""

from pathlib import Path
import os # <-- ADD THIS LINE
import certifi # <-- ADD THIS LINE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2^a=^*k312jbi7ms%-ymd*%ety5wx@-=o*3+m7%^105@o%)rl6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- ADD/VERIFY THESE ---
    'rest_framework',           # The API framework
    'rest_framework.authtoken', # The token authentication app
    'corsheaders',              # Handles cross-origin requests from React
    'core',                     # Your `core` app (for transactions, etc.)
]

MIDDLEWARE = [
    # --- ADD THIS AT THE VERY TOP OF THE LIST ---
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crypto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <-- ADD THIS LINE
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crypto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# <-- MODIFIED SECTION FOR MONGODB ATLAS -->
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'CLIENT': {
           'host': 'mongodb+srv://crypto_db:crypto123@crypto.qn25tf1.mongodb.net/crypto_db', # Specify the DB name at the end
           'tls': True,
           'tlsCAFile': certifi.where(),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# <-- ADD THESE LINES FOR YOUR STATIC FILES -->
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Configure Django REST Framework to use TokenAuthentication by default
# Tell DRF to use TokenAuthentication by default for all API views
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# IMPORTANT: Set this to your React app's URL
# This tells the backend to accept requests from your frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # The default Vite dev server URL
    "http://10.69.177.201:8080",
]